name: flask_api
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.1=py36_0
  - altair=3.1.0=py36_0
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - astor=0.7.1=py36_0
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - branca=0.3.1=py_0
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.15.0=h1de35cc_1
  - ca-certificates=2019.5.15=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2019.6.16=py36_0
  - cffi=1.12.3=py36hb5b8e2f_0
  - chardet=3.0.4=py36_1
  - click=7.0=py36_0
  - click-plugins=1.1.1=py_0
  - cryptography=2.7=py36ha12b0ac_0
  - curl=7.65.2=ha441bb4_0
  - cycler=0.10.0=py36hfc81398_0
  - dbus=1.13.6=h90a0687_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py36_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=h0a44026_0
  - fiona=1.8.4=py36h9a122fd_0
  - flask=1.1.1=py_0
  - folium=0.10.0=py_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - freexl=1.0.5=h1de35cc_0
  - future=0.17.1=py36_0
  - gast=0.2.2=py36_0
  - gdal=2.3.3=py36hbe65578_0
  - geopandas=0.4.1=py_0
  - geos=3.7.1=h0a44026_0
  - gettext=0.19.8.1=h15daf44_3
  - giflib=5.1.4=h1de35cc_1
  - glib=2.56.2=hd9629dc_0
  - grpcio=1.16.1=py36h044775b_1
  - h5py=2.9.0=py36h3134771_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.10.4=hfa1e0ec_0
  - icu=58.2=h4b95b61_1
  - idna=2.8=py36_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.1=py36h39e3cac_0
  - ipython=7.6.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - ipywidgets=7.5.0=py_0
  - itsdangerous=1.1.0=py36_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py36_0
  - jpeg=9b=he5867d9_2
  - json-c=0.13.1=h3efe00b_0
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.3.1=py_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.5.0=py_0
  - kealib=1.4.7=hf5ed860_6
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py36h0a44026_0
  - krb5=1.16.1=hddcf347_7
  - libboost=1.67.0=hebc422b_4
  - libcurl=7.65.2=h051b688_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libdap4=3.19.1=h3d3e54a_0
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgdal=2.3.3=h0950a36_0
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libkml=1.3.0=hbe12b63_4
  - libnetcdf=4.6.1=hd5207e6_2
  - libpng=1.6.37=ha441bb4_0
  - libpq=11.2=h051b688_0
  - libprotobuf=3.8.0=hd9629dc_0
  - libsodium=1.0.16=h3efe00b_0
  - libspatialindex=1.8.5=h2c08c6b_2
  - libspatialite=4.3.0a=h644ec7d_19
  - libssh2=1.8.2=ha12b0ac_0
  - libtiff=4.0.10=hcb84e12_2
  - libxml2=2.9.9=hf6e021a_1
  - mapclassify=2.0.1=py_0
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.1.0=py36h54f8f79_0
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.0.2=py36h1de35cc_0
  - mkl_fft=1.0.12=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - mock=3.0.5=py36_0
  - munch=2.3.2=py36_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.0=py36_0
  - numpy=1.16.4=py36hacdab7b_0
  - numpy-base=1.16.4=py36h6575580_0
  - olefile=0.46=py36_0
  - openjpeg=2.3.0=hb95cd4c_1
  - openssl=1.1.1c=h1de35cc_1
  - pandas=0.24.2=py36h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.0=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.1.0=py36hb68e598_0
  - pip=19.1.1=py36_0
  - pixman=0.38.0=h1de35cc_0
  - poppler=0.65.0=ha097c24_1
  - poppler-data=0.4.9=0
  - proj4=5.2.0=h0a44026_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py36_0
  - protobuf=3.8.0=py36h0a44026_0
  - psycopg2=2.7.6.1=py36ha12b0ac_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.0=py_0
  - pyproj=1.9.6=py36h9c430a6_0
  - pyqt=5.9.2=py36h655552a_2
  - pyrsistent=0.14.11=py36h1de35cc_0
  - pysocks=1.7.0=py36_0
  - python=3.6.8=haf84260_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.1=py_0
  - pyyaml=5.1.1=py36h1de35cc_0
  - pyzmq=18.0.0=py36h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.5.2=py_0
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py36_0
  - rtree=0.8.3=py36_0
  - scipy=1.3.0=py36h1410ff5_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.0.1=py36_0
  - shapely=1.6.4=py36he8793f5_0
  - simplejson=3.16.0=py36h1de35cc_0
  - sip=4.19.8=py36h0a44026_0
  - six=1.12.0=py36_0
  - sqlalchemy=1.3.5=py36h1de35cc_0
  - sqlite=3.29.0=ha441bb4_0
  - tensorboard=1.13.1=py36haf313ee_0
  - tensorflow=1.13.1=mkl_py36haf07a9b_0
  - tensorflow-base=1.13.1=mkl_py36hc36dc97_0
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - urllib3=1.24.2=py36_0
  - vincent=0.4.4=py_1
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.15.4=py_0
  - wheel=0.33.4=py36_0
  - widgetsnbextension=3.5.0=py36_0
  - xerces-c=3.2.2=h44e365a_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - affine==2.2.2
    - cligj==0.5.0
    - coverage==4.5.4
    - cython==0.29.12
    - keras-resnet==0.2.0
    - keras-retinanet==0.4.1
    - laspy==1.5.1
    - laxpy==0.1.5
    - llvmlite==0.29.0
    - numba==0.45.0
    - opencv-contrib-python==4.1.0.25
    - opencv-python==4.1.0.25
    - plyfile==0.7
    - psutil==5.6.3
    - pyfor==0.3.4
    - python-coveralls==2.9.2
    - rasterio==1.0.24
    - slidingwindow==0.0.13
    - snuggs==1.4.6
    - xmltodict==0.12.0
prefix: /Users/ben/miniconda3/envs/flask_api
